-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Хост: 127.0.0.1
-- Время создания: Дек 13 2024 г., 21:25
-- Версия сервера: 10.4.32-MariaDB
-- Версия PHP: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- База данных: `dariya`
--

-- --------------------------------------------------------

--
-- Структура таблицы `recipes`
--

CREATE TABLE `recipes` (
  `id` int(11) NOT NULL,
  `name` text NOT NULL,
  `photo` text NOT NULL,
  `is_gluten_free` tinyint(1) NOT NULL,
  `is_sugar_free` tinyint(1) NOT NULL,
  `is_vegetarian` tinyint(1) NOT NULL,
  `cooktime` text NOT NULL,
  `description` text NOT NULL,
  `category` enum('breakfast','main','snack','dessert','soup','salad') NOT NULL,
  `ingredients` text NOT NULL,
  `steps` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Дамп данных таблицы `recipes`
--

INSERT INTO `recipes` (`id`, `name`, `photo`, `is_gluten_free`, `is_sugar_free`, `is_vegetarian`, `cooktime`, `description`, `category`, `ingredients`, `steps`) VALUES
(3, 'No-Added Sugar Banana Bread', 'pics/no-added-sugar-banana-bread.png', 1, 1, 0, '1 hour 5 mins', 'This almond flour banana bread recipe creates a moist, gluten-free loaf sweetened naturally with ripe bananas, with a light, nutty flavor perfect for a healthy treat.', 'snack', '3 very ripe medium bananas, mashed (this should measure to be 1 ¼ cups mashed banana)\r\n3 eggs\r\n3 tablespoons unsweetened almond milk\r\n1 teaspoon vanilla extract\r\n2 ½ cups packed blanched fine almond flour (I use Bob\'s Red MIll)\r\n½ cup flaxseed meal\r\n1 teaspoon cinnamon\r\n1 teaspoon baking soda\r\n½ teaspoon salt\r\ndesired nuts', '<li>Preheat oven to 350°F and line a loaf pan with parchment paper.\r\n<li>Mix mashed bananas, eggs, honey, vanilla, and almond butter in a bowl.\r\n<li>Add almond flour, baking soda, cinnamon, and salt, then stir until well combined.\r\n<li>Fold in chocolate chips or nuts if desired.\r\n<li>Pour the batter into the pan and smooth the top.\r\n<li>Bake for 50-60 minutes, until golden and a toothpick comes out clean.\r\n<li>Let cool in the pan, then transfer to a wire rack.'),
(4, 'Miso soup', 'pics/miso-soup.png', 1, 1, 0, '5 mins', 'This miso soup is full of savory flavors. Add more dashi to your soup if you want a stronger stock. You can use yellow, white, or red miso paste for this soup — yellow miso is sweet and creamy, red miso is stronger and saltier.', 'soup', '4 cups water \r\n2 teaspoons dashi granules \r\n3 tablespoons miso paste \r\n1 (8 ounce) package silken tofu, diced \r\n2 green onions, sliced diagonally into 1/2 inch pieces', '<li>Gather all ingredients.\r\n<li>Combine water and dashi granules in a medium saucepan over medium-high heat; bring to a boil.\r\n<li>Reduce heat to medium and whisk in miso paste.\r\n<li>Stir in tofu.\r\n<li>Separate the layers of green onions, and add them to the soup. Simmer gently for 2 to 3 minutes before serving.\"'),
(5, 'Lemon-Blueberry Frozen Yogurt Bites', 'pics/lemon-blueberry-frozen-yogurt-bites.png', 1, 1, 0, '2.5 hours', 'These lemon-blueberry frozen yogurt bites, filled with probiotic yogurt and plenty of prebiotic blueberries, will help keep your gut in tip-top shape. This easy frozen snack is versatile, too—swap out the blueberries for raspberries or strawberries for a different twist with the same health benefits.', 'dessert', '⅓ cup freeze-dried blueberries \r\n1 cup whole-milk plain strained (Greek-style) yogurt \r\n2 tablespoons vanilla extract \r\n2 teaspoons grated lemon zest \r\n¼ teaspoon ground cardamom or  cinnamon \r\n⅛ teaspoon salt \r\n2 cups fresh blueberries', '<li>Line a large baking sheet with parchment paper. Place ⅓ cup freeze-dried blueberries in a zip-top plastic bag. Using a rolling pin, crush the berries into a very fine powder. Transfer the powder to a medium bowl; stir in 1 cup yogurt, 2 tablespoons vanilla, 2 teaspoons lemon zest, ¼ teaspoon cardamom (or cinnamon) and ⅛ teaspoon salt until smooth. Add 2 cups blueberries; stir to coat.\r\n<li>Using a fork, remove 1 blueberry from the yogurt, tapping excess yogurt off; use a wooden pick to push the blueberry off the fork onto the prepared baking sheet. Repeat with the remaining blueberries, leaving space between them. Place the baking sheet, uncovered, in the freezer until the bites are frozen, at least 2 hours and up to 24 hours. Remove from the freezer 5 minutes before serving.'),
(6, 'Roasted Butternut Squash Salad', 'pics/roasted-butternut-squash-salad.png', 1, 0, 1, '1 hour', 'This roasted butternut squash salad, with its caramelized butternut squash, tender kale and a zingy dressing, makes the perfect dish. Whether paired with roasted chicken or seared steak or enjoyed on its own, it brings a balance of sweet and savory to the table, making it a crowd-pleaser at any gathering. ', 'salad', '1 medium butternut squash, peeled, seeded and cut into\r\n ½-inch pieces (about 6 cups)\r\n 5 tablespoons extra-virgin olive oil, divided \r\n½ teaspoon ground pepper, divided \r\n2 tablespoons pomegranate juice \r\n1 tablespoon cider vinegar \r\n1 tablespoon pure maple syrup\r\n 2 teaspoons whole-grain mustard\r\n 1 teaspoon grated orange zest \r\n½ teaspoon salt, divided \r\n8 cups chopped lacinato kale \r\n½ cup thinly sliced scallions\r\n ⅓ cup shaved Parmesan cheese ⅓ cup pomegranate arils \r\n¼ cup unsweetened dried cranberries \r\n¼ cup chopped pecans, toasted', '<li>Preheat oven to 425°F with rack in upper third position. Toss squash with 1 tablespoon oil and ¼ teaspoon pepper on a large rimmed baking sheet until well coated; spread in an even layer. Roast, stirring once, until tender, about 30 minutes. Leaving the squash in the oven, increase oven temperature to broil. Broil until browned, about 2 minutes. Let cool slightly on the baking sheet, about 5 minutes.\r\n<li>Meanwhile, whisk 2 tablespoons pomegranate juice, 1 tablespoon each vinegar and maple syrup, 2 teaspoons mustard, 1 teaspoon orange zest, ¼ teaspoon salt and the remaining 4 tablespoons oil and ¼ teaspoon pepper in a small bowl until well combined.\r\n<li>Place 8 cups kale in a large bowl; drizzle with 1 tablespoon of the pomegranate vinaigrette. Massage with clean hands until the kale is bright green and the volume has reduced by about half, about 1 minute. Add the roasted squash, ½ cup scallions, ⅓ cup each Parmesan and pomegranate arils, ¼ cup cranberries and the remaining pomegranate vinaigrette and ¼ teaspoon salt; toss until evenly combined. Top with ¼ cup pecans.'),
(7, 'Cajun-Spiced Tofu Tostadas with Beet Crema', 'pics/cajun-spiced-tofu-tostadas-with-beet-crema.png', 1, 1, 1, '35 mins', 'Crumbled tofu spiced up with Cajun seasoning is layered onto these tostadas with a juicy mango slaw. A dollop of sour cream zhuzhed up with beet and lime adds even more flavor. Look for precooked beets in the produce department of your grocery store.', 'main', '8 corn tortillas\r\n2 tablespoons avocado oil, divided \r\n3 cups shredded cabbage \r\n½ mango, julienned  \r\n2 tablespoons lime juice, divided \r\n1 tablespoon chopped fresh cilantro \r\n¾ teaspoon salt, divided \r\n1 small cooked beet, shredded \r\n⅓ cup sour cream \r\n1 small clove garlic, grated \r\n1 14- to 16-ounce package extra-firm tofu, drained, crumbled and patted dry \r\n2 tablespoons salt-free Cajun seasoning \r\n1 avocado, diced', '<li>Position a rack in upper third of oven; preheat to 400°F.\r\n<li>Brush both sides of tortillas with 1 tablespoon oil and arrange on a baking sheet. (It\'s OK if they overlap a bit; they will shrink as they cook.) Bake, turning once halfway, until browned and very crisp, 10 to 12 minutes. Transfer to a wire rack and let cool.\r\n<li>Meanwhile, toss cabbage, mango, 1 tablespoon lime juice, cilantro and 1/4 teaspoon salt in a medium bowl. Combine beet, sour cream, garlic, the remaining 1 tablespoon lime juice and 1/4 teaspoon salt in a small bowl.\r\n<li>Heat the remaining 1 tablespoon oil in a large cast-iron skillet over medium-high heat. Add tofu, Cajun seasoning and the remaining 1/4 teaspoon salt. Cook, stirring occasionally, until nicely browned, 8 to 10 minutes.\r\n<li>Top the tostadas with the tofu, slaw, beet crema and avocado.'),
(8, 'Chocolate Zucchini Cake', 'pics/chocolate-zucchini-cake.png', 0, 0, 0, '1 hour 50 minutes', 'This zucchini chocolate cake is a celebration of the unexpected magic that happens when humble ingredients like shredded zucchini, cocoa powder and chocolate chips come together in perfect harmony. Whether enjoyed with a steaming cup of weekday coffee or served at a gathering, this chocolate zucchini cake is sure to steal the spotlight. ', 'dessert', '1 1/4 cups whole-wheat flour\r\n1 1/4 cups all-purpose flour\r\n3/4 cup cocoa powder\r\n2 teaspoons baking powder\r\n1/2 teaspoon salt\r\n1 cup packed light brown sugar\r\n2/3 cup canola oil\r\n1/2 cup buttermilk\r\n4 large eggs\r\n6 tablespoons granulated sugar\r\n2 teaspoons vanilla extract\r\n2 1/2 cups shredded zucchini (about 2 medium)\r\n3/4 cup semisweet chocolate chips\r\n1 (8-ounce) package reduced-fat cream cheese, at room temperature\r\n2/3 cup confectioners\' sugar\r\n1/3 cup low-fat plain strained (Greek-style) yogurt\r\n2 tablespoons whole milk\r\n1 teaspoon vanilla extract', '<li>Preheat oven to 350°F. Coat a 9-by-13-inch baking pan with cooking spray. Whisk whole-wheat flour, all-purpose flour, cocoa, baking powder and salt in a large bowl until well combined.\r\n<li>Whisk brown sugar, oil, buttermilk, eggs, granulated sugar and 2 teaspoons vanilla in a medium bowl until combined. Using a rubber spatula, gently fold the sugar mixture into the flour mixture until almost fully combined and a few dry streaks remain.\r\n<li>Fold zucchini and chocolate chips into the batter until evenly incorporated. Spread the batter evenly into the prepared baking pan.\r\n<li>Bake until a wooden pick inserted in the center comes out clean, about 30 minutes. Let cool completely in the pan on a wire rack, about 1 hour.\r\n<li>Combine cream cheese, confectioners’ sugar, yogurt, milk and vanilla in a medium bowl. Beat with an electric mixer on medium-high speed until smooth and creamy, 2 to 4 minutes. Spread the frosting evenly over the top of the cooled cake.'),
(9, 'Pear & Goat Cheese Upside-Down Puff Pastries', 'pics/pear-and-goat-cheese-upside-down-puff-pastries.png', 0, 1, 0, '40 mins', 'These easy tarts are the perfect holiday appetizer. With a blend of sweet fig jam, creamy goat cheese and juicy pear slices all baked in flaky puff pastry, they’re a crowd-pleasing combination of sweet and savory flavors. These tarts are simple to assemble, bake quickly, and add an elegant touch to any holiday spread.', 'snack', '7½ teaspoons fig jam, divided\r\n1 red Anjou or Barlett pear, unpeeled, cored and sliced ⅛-inch thick\r\n¾ cup crumbled goat cheese\r\n½ package frozen puff pastry (1 sheet), thawed and chilled\r\n1 large egg, lightly beaten\r\n¼ teaspoon cider vinegar\r\n¼ teaspoon flaky sea salt', '<li>Preheat oven to 400°F. Line a large rimmed baking sheet with parchment paper.\r\n<li>Spread 6 teaspoons fig jam into 6 (3-by-2-inch) rectangles on the prepared baking sheet, using 1 teaspoon for each and spacing about 2 inches apart.\r\n<li>Shingle about 4 pear slices over each jam rectangle; sprinkle 2 tablespoons goat cheese over the pears on each.\r\n<li>Cut puff pastry into 6 (about 3¼ inch by 4½ inch) rectangles; prick all over with a fork.\r\n<li>Place 1 pastry rectangle over each pear–goat cheese rectangle, stretching the pastry gently if necessary; gently press down the edges to seal in the fruit. Brush the tops with egg.\r\n<li>Bake until golden brown and flaky, 15 to 20 minutes, lightly covering with foil after 15 minutes. Using a spatula, flip the warm pastries pear-side up.\r\n<li>Whisk ¼ teaspoon cider vinegar and the remaining 1½ teaspoons fig jam in a small bowl until combined; drizzle evenly over the warm pastries. Sprinkle with ¼ teaspoon flaky sea salt.'),
(10, 'Crispy Curried Cauliflower Bites', 'pics/crispy-curried-cauliflower-bites.png', 0, 1, 0, '50 mins', 'These curried cauliflower bites are paired with a creamy dipping sauce that features kefir—a fermented, yogurt-like drink that’s rich in probiotics that can help support gut health. You can swap out the kefir for plain yogurt thinned with a little water if you prefer.', 'snack', '½ cup whole-milk plain kefir\r\n¼ cup cornstarch\r\n2 teaspoons curry powder\r\n½ teaspoon garlic powder\r\n½ teaspoon ground ginger\r\n½ cups panko breadcrumbs, preferably whole-wheat\r\n½ tablespoons extra-virgin olive oil\r\n4 cups cauliflower florets\r\n¼ teaspoon salt\r\n3 tablespoons whole-milk plain kefir\r\n3 tablespoons mayonnaise\r\n2 teaspoons chopped fresh mint, plus more for garnish\r\n½ teaspoon lime zest\r\n¼ teaspoon garlic powder\r\nPinch of  salt\r\nLime wedges for serving (optional)', '<li>Preheat oven to 400°F and line a large rimmed baking sheet with parchment paper.\r\n<li>Whisk ½ cup kefir, ¼ cup cornstarch, 2 teaspoons curry powder and ½ teaspoon each garlic powder and ginger in a medium bowl until a batter forms. Combine 1½ cups panko and 1½ tablespoons oil in a shallow dish; toss until coated.\r\n<li>Cut 4 cups cauliflower florets into bite-size pieces (about 1-inch). Working in 2 to 3 batches, add the cauliflower to the batter; toss until well coated. Dredge the coated cauliflower florets to the panko mixture, pressing to adhere. Place on the prepared baking sheet. (Discard any remaining panko mixture.) Roast, flipping once, until golden brown and crisp, about 30 minutes.\r\n<li>Combine 3 tablespoons each kefir and mayonnaise, 2 teaspoons mint, ½ teaspoon lime zest, ¼ teaspoon garlic powder and a pinch of salt in a small bowl; whisk until smooth. Sprinkle the cauliflower with additional mint, if desired. Serve with the Kefir-Mint Dipping Sauce and with lime wedges, if desired.'),
(11, 'Raspberry-Jam Bites', 'pics/raspberry-jam-bites.png', 1, 1, 0, '1 hour 20 minutes', 'This simple, three-ingredient snack. Chia seeds and raspberries add fiber to these healthy frozen bites. Chocolate provides a touch of sweetness to balance the tartness of the berries.', 'dessert', '16 ounces fresh raspberries (about 4 cups) or 3 1/2 cups frozen raspberries\r\n2 tablespoons chia seeds\r\n12 ounces dark chocolate (60-70%), chopped', '<li>Line a large baking sheet with parchment paper. Place raspberries and chia seeds in a large bowl. Mash with a fork until the mixture is jammy. (If using frozen raspberries, add 1/4 cup water, 1 tablespoon at a time, until the berries are loosened.) Scoop the mixture by heaping tablespoonfuls onto the prepared baking sheet. Freeze for at least 1 hour or up to 8 hours.\r\n<li>Line another baking sheet with parchment paper. Microwave chocolate in a medium microwave-safe bowl on Medium for 1 minute. Stir, then continue microwaving on Medium in 20-second intervals until melted, stopping to stir after each interval. (Alternatively, place chocolate in the top of a double boiler over hot, but not boiling, water; stir until melted.)\r\n<li>Remove the raspberry bites from the freezer. Using a fork, hold one bite over the melted chocolate and use a spoon to lightly coat it, allowing excess chocolate to drip back into the bowl. Spoon about 1 teaspoon melted chocolate onto the parchment paper and place the coated bite on top. Repeat the process with the remaining bites. Use a spoon or fork to drizzle the tops of the bites with the remaining chocolate, if desired. Serve immediately or store in an airtight container in the freezer for up to 1 month.'),
(12, 'Veggie Wraps', 'pics/veggie-wraps.png', 0, 1, 1, '15 mins', 'These wraps are packed with veggies, including zucchini, bell pepper and spinach. The vegetables cook quickly in a skillet, so you can pull together this easy lunch in no time. Hummus adds plant-based protein and keeps the wrap from getting dry.', 'main', '1 teaspoon extra-virgin olive oil\r\n½ small zucchini, sliced\r\n½ medium red bell pepper, sliced\r\n¼ small red onion, sliced\r\n½ teaspoon dried oregano\r\nPinch of salt\r\n2 whole-grain wraps\r\n¼ cup hummus\r\n½ cup baby spinach\r\n2 tablespoons crumbled feta cheese\r\n4 black olives, sliced', '<li>Heat 1 teaspoon oil in a small skillet over medium-low heat. Add sliced zucchini, bell pepper and onion, ½ teaspoon oregano and a pinch of salt; cook, stirring, until soft, 5 to 7 minutes.\r\n<li>Place 2 wraps on a clean work surface. Divide ¼ cup hummus between the wraps; spread evenly. Divide ½ cup spinach between the wraps. Top with the sautéed vegetables. Sprinkle with 2 tablespoons feta and sliced olives. Roll each wrap up and cut in half.'),
(13, 'Baked Feta & Tomato Spaghetti Squash', 'pics/baked-feta-and-tomato-spaghetti-squash.png', 1, 1, 0, '1 hour 10 minutes', 'This easy baked spaghetti squash recipe is a showstopper on any table. Baking the feta and tomatoes in the squash half results in a lovely sauce when everything is mixed together. The balsamic glaze adds a nice bit of sweetness while playing up the acidity of the tomatoes. ', 'main', '1 medium spaghetti squash, halved lengthwise and seeded (3- to 3½-lb.)\r\n3 tablespoons extra-virgin olive oil, divided\r\n1/4 teaspoon crushed red pepper\r\n1/4 teaspoon ground pepper\r\n1/8 teaspoon salt\r\n1 (4-oz.) block feta cheese, halved\r\n8 ounces cherry tomatoes (about 1 1/2 cups)\r\n3 tablespoons chopped fresh basil, plus more for garnish\r\n1 tablespoon minced garlic\r\n1/2 teaspoons chopped fresh oregano\r\n1 tablespoon balsamic glaze', '<li>Position rack in middle of oven; preheat to 400°F. Line a large rimmed baking sheet with parchment paper or foil.\r\n<li>Place squash halves, cut-sides up, on the prepared baking sheet. Drizzle with 1 tablespoon oil; sprinkle with crushed red pepper, pepper and salt. Place 1 feta piece, ¾ cup tomatoes, 1½ tablespoons basil, 1½ teaspoons garlic and ¾ teaspoon oregano in each squash half. Drizzle each with 1½ teaspoons oil. Bake until the squash flesh is tender and the tomatoes burst, 50 to 55 minutes\r\n<li>Remove from oven. Using a fork and tongs, scrape the squash contents and the long strands of squash flesh into a medium bowl. Drizzle in the remaining 1 tablespoon oil; stir to combine. Return the mixture to the squash shells; cut each in half widthwise. Transfer each to a plate; drizzle evenly with balsamic glaze and serve.\r\n'),
(14, 'Sheet-Pan Harissa Chicken & Vegetables', 'pics/sheet-pan-harissa-chicken-and-vegetables.png', 1, 1, 0, '35 mins', 'This one-pan dinner gets a hit of flavorful heat from harissa, the popular North African chile-and-garlic paste. We use harissa paste from a tube for this recipe. It\'s got a concentrated chile flavor that makes an excellent spice rub for chicken and adds a subtle punch of heat to a refreshing herbed yogurt sauce.', 'main', '4 cups white or purple cauliflower florets\r\n4 cups sliced red, orange and/or yellow bell peppers\r\n3 tablespoons extra-virgin olive oil, divided\r\n¼ teaspoon kosher salt, plus 1/2 teaspoon, divided\r\n2 teaspoons harissa paste, plus 1/2 teaspoon, divided\r\n1 teaspoon brown sugar\r\n1 clove garlic, minced\r\n8-ounce boneless, skinless chicken breasts\r\n½ cup whole-milk plain Greek yogurt\r\n1 teaspoon lemon zest\r\n2 tablespoons lemon juice\r\n1 teaspoon minced fresh mint\r\n1 teaspoon minced fresh parsley\r\n⅛ teaspoon ground pepper', '<li>Preheat oven to 400 degrees F. Toss cauliflower and peppers with 2 tablespoons oil and 1/4 teaspoon salt in a large bowl. Spread in a single layer on a large rimmed baking sheet; roast for 15 minutes.\r\n<li>Meanwhile, combine 2 teaspoons harissa paste, brown sugar, garlic and the remaining 1 tablespoon oil and 1/2 teaspoon salt in a small bowl. Rub chicken all over with the harissa mixture. Stir the vegetables, then add the chicken to the pan. Roast until a thermometer inserted into the thickest part of the chicken registers 165 degrees F, about 20 minutes.\r\n<li>Combine yogurt, the remaining 1/2 teaspoon harissa paste, lemon zest and juice, mint, parsley and pepper in a small bowl. Drizzle the sauce over the chicken and vegetables or serve on the side for dipping.'),
(15, 'Carrot Soup\r\n', 'pics/carrot-soup.png', 1, 0, 0, '50 mins', 'This easy carrot soup recipe is a great way to use up a bag of carrots that were forgotten in your produce drawer. The carrots cook together with aromatics like onions, garlic and fresh herbs before being pureed into a silky smooth soup that\'s delicious for dinner or packed up for lunch.', 'soup', '1 tablespoon butter\r\n1 tablespoon extra-virgin olive oil\r\n1 medium onion, chopped\r\n1 stalk celery, chopped\r\n2 cloves garlic, chopped\r\n1 teaspoon chopped fresh thyme or parsley\r\n5 cups chopped carrots\r\n2 cups water\r\n4 cups reduced-sodium chicken broth, \"\"no-chicken\"\" broth (see Note) or vegetable broth\r\n½ cup half-and-half (optional)\r\n½ teaspoon salt\r\n¼ teaspoon freshly ground pepper to taste', '<li>Heat butter and oil in a Dutch oven over medium heat until the butter melts. Add onion and celery; cook, stirring occasionally, until softened, 4 to 6 minutes. Add garlic and thyme (or parsley); cook, stirring, until fragrant, about 10 seconds. Stir in carrots. Add water and broth; bring to a lively simmer over high heat. Reduce heat to maintain a lively simmer and cook until very tender, about 25 minutes.\r\n<li>Puree the soup in batches in a blender until smooth. (Use caution when pureeing hot liquids.) Stir in half-and-half (if using), salt and pepper.\"'),
(16, 'Berry-Kefir Smoothie', 'pics/berry-kefir-smoothie.png', 1, 1, 0, '5 mins', 'Get a probiotic boost at breakfast when you add kefir to your smoothie. Feel free to use any berries and nut butter you have on hand in this healthy smoothie recipe.', 'dessert', '1 ½ cups frozen mixed berries\r\n1 cup plain kefir\r\n½ medium banana\r\n2 teaspoons almond butter\r\n½ teaspoon vanilla extract', '<li>Combine berries, kefir, banana, almond butter and vanilla in a blender. Blend until smooth.'),
(17, 'High-Protein Cinnamon-Roll Oatmeal', 'pics/high-protein-cinnamon-roll-oatmeal.png', 0, 1, 0, '15 mins', 'Flavored with cinnamon, vanilla, maple syrup and a Greek-style yogurt “frosting,” this cinnamon-roll oatmeal is a winning breakfast worth waking up for. Oats offer lots of filling fiber to help keep you full and your heart healthy. Add toasted chopped walnuts if you want a little extra crunch.', 'breakfast', '2 cups nonfat milk\r\n1 cup old-fashioned rolled oats\r\n5 pieces of dates\r\n1 teaspoon cinnamon\r\n1 teaspoon vanilla extract\r\nPinch of salt\r\n2 tablespoons nonfat plain strained (Greek-style) yogurt', '<li>Place 2 cups milk in a medium saucepan; bring to a gentle boil over medium heat. Stir in 1 cup oats; reduce heat to maintain a gentle simmer and cook, stirring frequently, until the oats have softened and thickened, 7 to 9 minutes. Remove from heat.\r\n<li>Add 3 teaspoons maple syrup, 1 teaspoon each cinnamon and vanilla and a pinch of salt to the oats. Divide the oatmeal between 2 bowls.\r\n<li>Stir 2 tablespoons yogurt and the remaining 1 teaspoon maple syrup together in a small bowl. Drizzle over the top of the oatmeal.'),
(18, 'Avocado Smoothie', 'pics/avocado-smoothie.png', 1, 1, 1, '5 mins', 'Don’t worry – this avocado smoothie doesn’t taste at all like guacamole. Instead, it’s like a fresh lime sorbet. Thanks to the avocado and banana, it has a delicious creamy texture that makes it a really satisfying breakfast or snack. In fact, it’s so good that I’d even eat it for dessert!', 'dessert', '½ cup frozen pineapple\r\n2 cups packed fresh spinach, or 1 cup frozen spinach\r\n1 ripe avocado\r\n1 frozen banana\r\n¾ cup light coconut milk, canned or from a carton\r\n3 tablespoons fresh lime juice\r\n½ teaspoon lime zest\r\n1 teaspoon maple syrup\r\nPinch sea salt\r\n8 ice cubes\r\n2 scoops vanilla protein powder*, optional', '<li>Combine the pineapple, spinach, avocado, banana, coconut milk, lime juice and zest, maple syrup, salt, ice, and protein powder, if using, in a blender. Blend until creamy.\r\n<li>Taste and adjust the sweetness to your liking. If you prefer a sweeter smoothie, add more maple syrup. If the consistency is too thick, add more coconut milk, and blend again.');

--
-- Индексы сохранённых таблиц
--

--
-- Индексы таблицы `recipes`
--
ALTER TABLE `recipes`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT для сохранённых таблиц
--

--
-- AUTO_INCREMENT для таблицы `recipes`
--
ALTER TABLE `recipes`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=19;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
